Delete ElasticSearch 4 EVER
Tall-Programacion-FIME/backend pull request #50
Opened 2021-05-11 05:44 UTC by HectorMtz22

2021-05-11 05:45 UTC, HectorMtz22 commented
No pasará aún los tests por cuestión que no los edité y sigue buscando ElasticSearch

2021-05-11 12:38 UTC, sebastianmarines requested changes
Hay que hacer todas las modificaciones, y en los tests modificar esto:
https://github.com/Tall-Programacion-FIME/backend/blob/a545a9e205b691e11a119080ca27698ca5768e61/app/app/tests/conftest.py#L5
https://github.com/Tall-Programacion-FIME/backend/blob/a545a9e205b691e11a119080ca27698ca5768e61/app/app/tests/conftest.py#L16-L18
Con esto ya deben de pasar las pruebas.

2021-05-11 12:38 UTC, sebastianmarines commented on app/app/crud/crud_book.py
> -    background_tasks: BackgroundTasks, db: Session, es: Elasticsearch, book_id: int
Hay que dejar el parámetro background_tasks

2021-05-11 12:38 UTC, sebastianmarines commented on app/app/crud/crud_book.py
> -    )
Regresar este bloque de código. Es necesario para borrar las imágenes de S3

2021-05-11 12:38 UTC, sebastianmarines commented on app/app/routers/endpoints/book.py
> +    crud.delete_book(db, book_id=book_id)
Hay que enviar background_tasks a la función

2021-05-11 12:38 UTC, sebastianmarines commented on app/app/routers/endpoints/user.py
> -    es: Elasticsearch = Depends(get_es),
Eliminar `es=es` en la linea **89**
https://github.com/Tall-Programacion-FIME/backend/blob/a545a9e205b691e11a119080ca27698ca5768e61/app/app/routers/endpoints/user.py#L89

2021-05-12 00:31 UTC, HectorMtz22 commented
# Ya pasaron los teeestss

2021-05-12 00:34 UTC, sebastianmarines approved these changes

2021-05-12 00:34 UTC, merged